### ISSUE TITLE
command_control.py SyntaxError

### ISSUE THREAD

**Issue by HawaYann** [austin-taylor/flare#55]
Hello,

I pull last version, during "python setup.py install" I noted an error and when tried to execute flare same error:
"
Traceback (most recent call last):
  File "/usr/local/bin/flare_beacon", line 4, in <module>
    __import__('pkg_resources').run_script('Flare==0.4', 'flare_beacon')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/Flare-0.4-py3.7.egg/EGG-INFO/scripts/flare_beacon", line 8, in <module>
    from flare.analytics.command_control import elasticBeacon
  File "/usr/local/lib/python3.7/dist-packages/Flare-0.4-py3.7.egg/flare/analytics/command_control.py", line 308
    self.dprint(df)
       ^
SyntaxError: invalid syntax
"
My fix was to pull command_control.py from your previous branch and replace it, and that resolved my issue. No error anymore.
I did not dig in the code, but perhaps something is wrong with the last version of command_control.py or I missed something?

Thank you.

**Comment by HawaYann** [comment]
I found the issue the issue was on line 304, missing ")" at the end of the line:

Original:
`df.rename(columns=dict((x, x.replace("_source.", "")) for x in df.columns), inplace=True`

change to :
`df.rename(columns=dict((x, x.replace("_source.", "")) for x in df.columns), inplace=True)`

this patch fixed the issue for me.

Hope that help!

**Comment by SMAPPER** [comment]
Thank you. You are spot on. This is fixed.
